spring:
  config:
    activate:
      on-profile: "prod"

build:
  version: "1.0"

accounts:
  message: "Welcome to Eazybanks accounts microservice for Prod environment"
  contactDetails:
    name: "Keyuri Aishwarya - Product owner"
    email: "aishwarya@eazybanks.com"
  onCallSupport:
    - (999) 555-2253
    - (999) 555-3283